[project]
name = "short-fetcher"
version = "0.1.0"
description = "Fetch the description of youtube short"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-api-python-client>=2.187.0",
    "streamlit>=1.52.2",
    "youtube-transcript-api>=1.2.3",
]
